language : node_js
node_js :
 - stable
install:
 - npm install
script:
 - echo "Running tests against $(node -v)..."
 - npm test
after_script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage